[package]
name = "ojo-builder"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
authors.workspace = true
description = "Build-time code generation for Ojo event schemas"

[dependencies]
fnv.workspace = true
