[package]
name = "simple-example"
version = "0.1.0"
edition = "2021"

[dependencies]
ojo-client = { path = "../../crates/ojo-client" }
rand = "0.9"

[build-dependencies]
ojo-builder = { path = "../../crates/ojo-builder" }
